spring:
  profiles:
    active:
    - test
---
server: 
  port: 5001

spring:
  profiles: dev
  application:
    name: eureka5001-dev
     
eureka: 
  instance: 
    hostname: eureka5001.com #冒号后面必须要有空格
  client: 
    register-with-eureka: false  #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #单机注册本地
---
server:
  port: 5002 #注册中心占用7001端口，冒号后面必须要有空格
  
spring:
  profiles: test
  application:
    name: eureka5002-test
    
eureka: 
  instance: 
    hostname: eureka5002.com #冒号后面必须要有空格
  client: 
    register-with-eureka: false  #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #单机注册本地