spring:
  profiles:
    active:
    - dev
---
server:
  port: 5001
spring:
  application:
    name: myfirst-provider-dept
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB01?characterEncoding=UTF-8&useSSL=false&connectTimeout=2000&socketTimeout=10000
    username: root
    password: root
  
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: config-provider-dev
    prefer-ip-address: true
    
---
server:
  port: 5002
spring:
  application:
    name: myfirst-provider-dept
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB02?characterEncoding=UTF-8&useSSL=false&connectTimeout=2000&socketTimeout=10000
    username: root
    password: root

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: config-provider-test
    prefer-ip-address: true