spring:
  profiles:
   active:
   - dev
---
server:
  port: 5001
spring:
  profiles: dev  #开发环境
  application:
   name: springcloudfirst-config-read-dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 5002
spring:
  profiles: test  #测试环境
  application:
   name: springcloudfirst-config-read-test
eureka:
  client:
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/
